-- Mirrors prisma/schema.prisma exactly.
-- This file exists ONLY because binaries.prisma.sh is unreachable in the
-- build sandbox, so `prisma migrate dev` cannot run here. It is used to
-- verify the schema and seed logic against a real local Postgres instance.
-- The actual migration history should be generated by running
-- `npx prisma migrate dev --name init` in a normal dev environment.

CREATE TYPE "AgentCategory" AS ENUM ('REBALANCING', 'GRID_TRADING', 'YIELD_OPTIMIZATION', 'HEALTH_FACTOR');
CREATE TYPE "DataSource" AS ENUM ('VERIFIED_ONCHAIN', 'VERIFIED_EXTERNAL', 'MARKETPLACE_DERIVED', 'SELF_REPORTED', 'DEMO');
CREATE TYPE "RiskLevel" AS ENUM ('LOW', 'MEDIUM', 'HIGH');
CREATE TYPE "HireStatus" AS ENUM ('SIMULATED', 'ONCHAIN');

CREATE TABLE "Agent" (
  "id" TEXT PRIMARY KEY,
  "name" TEXT NOT NULL,
  "slug" TEXT NOT NULL UNIQUE,
  "description" TEXT NOT NULL,
  "category" "AgentCategory" NOT NULL,
  "capabilities" TEXT[] NOT NULL,
  "supportedProtocols" TEXT[] NOT NULL,
  "supportedChains" TEXT[] NOT NULL,
  "creator" TEXT NOT NULL,
  "pricingModel" TEXT NOT NULL,
  "pricingSource" "DataSource" NOT NULL DEFAULT 'SELF_REPORTED',
  "executionModel" TEXT NOT NULL,
  "status" TEXT NOT NULL DEFAULT 'active',
  "erc8004Id" TEXT,
  "erc8004Verified" BOOLEAN NOT NULL DEFAULT false,
  "walletAddress" TEXT,
  "dataSource" "DataSource" NOT NULL DEFAULT 'DEMO',
  "createdAt" TIMESTAMP NOT NULL DEFAULT now(),
  "updatedAt" TIMESTAMP NOT NULL DEFAULT now()
);
CREATE INDEX "Agent_category_idx" ON "Agent"("category");

CREATE TABLE "AgentMetrics" (
  "id" TEXT PRIMARY KEY,
  "agentId" TEXT NOT NULL UNIQUE REFERENCES "Agent"("id"),
  "executionsCount" INTEGER NOT NULL,
  "successRatePct" DOUBLE PRECISION NOT NULL,
  "uptimePct" DOUBLE PRECISION NOT NULL,
  "avgCostUsd" DOUBLE PRECISION NOT NULL,
  "avgLatencySec" DOUBLE PRECISION NOT NULL,
  "lastActiveAt" TIMESTAMP NOT NULL,
  "source" "DataSource" NOT NULL DEFAULT 'DEMO',
  "updatedAt" TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE "TrustScore" (
  "id" TEXT PRIMARY KEY,
  "agentId" TEXT NOT NULL UNIQUE REFERENCES "Agent"("id"),
  "score" INTEGER NOT NULL,
  "identityComponent" INTEGER NOT NULL,
  "performanceComponent" INTEGER NOT NULL,
  "reliabilityComponent" INTEGER NOT NULL,
  "activityComponent" INTEGER NOT NULL,
  "verificationComponent" INTEGER NOT NULL,
  "riskLevel" "RiskLevel" NOT NULL,
  "computedAt" TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE "Hire" (
  "id" TEXT PRIMARY KEY,
  "agentId" TEXT NOT NULL REFERENCES "Agent"("id"),
  "status" "HireStatus" NOT NULL DEFAULT 'SIMULATED',
  "txHash" TEXT,
  "createdAt" TIMESTAMP NOT NULL DEFAULT now()
);
